### ISSUE TITLE
Horizontal scrolling on screen that has enough space for vertical scrolling

### ISSUE THREAD

**Issue by mindhacker42** [ReveelTechnologies/web-plugin#2]
On screens that have enough space for vertical listview should have vertical list.

**URL tested:** https://reveeltechnologies.github.io/web-plugin/examples/jwplayerv7.html

Open [URL](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Freveeltechnologies.github.io%2Fweb-plugin%2Fexamples%2Fjwplayerv7.html&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://reveeltechnologies.github.io/web-plugin/examples/jwplayerv7.html) on Browserstack

|Property | Value|
|------------ | -------------|
| Device | Google Pixel 2 |
| Browser | Mobile_chrome |
| Operating System | Android 8.0 |
| Resolution | 1080 x 1920 px |
| Screen size | 5.74 in - 2.74 x 5.0 in |
| Viewport | 411 x 731 dp |
| Aspect Ratio | 16 : 9 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/6b67e2fd366bb0e3de46f7f2a323197581a02c7f/realdroid_Google_Pixel_2.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/6b67e2fd366bb0e3de46f7f2a323197581a02c7f/realdroid_Google_Pixel_2.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=android&os_version=8.0&device=Google+Pixel+2&device_browser=chrome&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Freveeltechnologies.github.io%2Fweb-plugin%2Fexamples%2Fjwplayerv7.html&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://reveeltechnologies.github.io/web-plugin/examples/jwplayerv7.html) to reproduce the issue on Browserstack**

**Comment by ajdnik** [comment]
Issue moved to private repo.
